In [1]:
import numpy as np

In [4]:
v = np.array([2, 15, 6])

In [5]:
print(type(v))

<class 'numpy.ndarray'>


In [6]:
# выведем на экран вектор s = (0, 8, 56, 11)
s = np.array([0, 8, 56, 11])
print(s)

[ 0  8 56 11]


In [7]:
# нулевой вектор можно задать 2 способами

vz_1 = np.array([0, 0, 0, 0])
vz_2 = np.zeros(4) # аргумент - количество координат

In [8]:
vz_1 == vz_2

array([ True,  True,  True,  True])

В аналитике данные можно представить в виде вектора. Например хотим указать параметры собаки по имени Бобик:

| возраст в месяцах | вес | рост в сантиметрах |
|-------------------|-----|---------------------|
| 10                | 12  | 30                  |

In [9]:
bobik = np.array([10, 12, 30])

## суммирование векторов

рассмотрим данные по месяцам - траты краски по литрам

| месяц | красная | синяя | зеленая  |  желтая |
|-----------|-----|-------|-------|-------|
| январь    | 10  | 20    | 30  |  0 |
| ферваль    | 0  | 30    | 54  |  20 |
| март    | 55  | 0    | 30  |  100 |
    

In [10]:
january = np.array([10, 20, 30, 0])
february = np.array([0, 30, 54, 20])
march = np.array([55, 0, 30, 100])

total = january + february + march
print(total)

[ 65  50 114 120]


## разность векторов
Это та же сумма векторов, только у второго вектора меняется направление, то есть знак. Только коммутативносе свойство уже не работает

In [11]:
difference = march - february
print(difference)

[ 55 -30 -24  80]


In [12]:
# отнимаем от всех сразу
difference - 2

array([ 53, -32, -26,  78])

In [13]:
# напишите код, который вычисляет сумму и разность векторов
k = np.array([47, 611, -58, 32, 0])
t = np.array([-20, 41, 899, 7, 14])

print(k - t)
print(k + t)

[  67  570 -957   25  -14]
[ 27 652 841  39  14]


In [14]:
# найдите разность суммы вектора a и b и суммы векторов c, d, e
a = np.array([2, 6, 32, 11])
b = np.array([65, 23, 0, 0])
c = np.array([309, 6, 14 ,7])
d = np.array([56, 48, 31, 2])
e = np.array([105, 11, 47, 34])

print(a + b - (c + d + e))

[-403  -36  -60  -32]


## умножение вектора на скаляр

Необходимо учеличить норму выработки на 20%
| рабочий | плиточник-1 | плиточник-2 | плиточник-3  |  плиточник-4 |
|-----------|-----|-------|-------|-------|
| выработка    | 3.6  | 4.8    | 4.2  |  7 |

In [15]:
work = np.array([3.6, 4.8, 4.2, 7])
new_work = work * 1.2
print(new_work)

[4.32 5.76 5.04 8.4 ]


## деление векторов
как и в арифметике - деление обратно умножению

In [16]:
work = np.array([3.6, 4.8, 4.2, 7])
min_work = work / 2 # аналог умножения на 0.5
print(min_work)

[1.8 2.4 2.1 3.5]


# Тригонометрия

In [17]:
np.sin(np.pi/6) # аргумент задается в радианах

0.49999999999999994

In [18]:
np.cos(np.pi/3)

0.5000000000000001

In [19]:
# перевод из радиан в градусы
np.rad2deg(1)

57.29577951308232

In [20]:
# из градусов в радианы
np.deg2rad(60)

1.0471975511965976

In [ ]:
# вычислим синус, косинус и тангенс для углов alpha = pi / 4 радиан и beta = 117 градусов
alpha = np.pi / 4
beta = np.deg2rad(117)

print(np.sin(alpha), np.cos(alpha), np.tan(alpha))
print(np.sin(beta), np.cos(beta), np.tan(beta))

0.7071067811865476 0.7071067811865476 0.9999999999999999
0.8910065241883679 -0.45399049973954675 -1.962610505505151


In [22]:
print(np.sin(alpha) == 2 ** 0.5 / 2)

True


In [23]:
# вычислим арксинус в градусах и радианах
x = - 5 / 12

print(np.rad2deg(np.arcsin(x)), np.arcsin(x))

-24.624318352164078 -0.4297754313045277


# Скалярное произведение векторов

In [30]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])

In [31]:
# старый способ записи скалярного произведения
a.dot(b)

14

In [32]:
# современный способ
a @ b

14

In [33]:
price = np.array([250, 300, 100, 500])
quantity = np.array([1, 1, 3, 2])

In [37]:
# price * quantity - координаты просто перемножаются
print(price * quantity)
sum(price * quantity) == price @ quantity == 1850

[ 250  300  300 1000]


True

# Линейные комбинации векторов

In [38]:
a_1 = np.array([45, 23, 6, 0, 18, 5])
a_2 = np.array([-6, 11, 8, 32, 9, 115])
a_3 = np.array([1, 2, 3, 4, 5, 6])
a_4 = np.array([318, 4, 0, 0, 0, -7])

k_1 = 3
k_2 = 11
k_3 = -5
k_4 = 7

In [39]:
a = k_1 * a_1 + k_2 * a_2 + k_3 * a_3 + k_4 * a_4
print(a)

[2290  208   91  332  128 1201]


# Нормы векторов

In [40]:
from numpy import linalg

### L1 норма
сумма по модулю всех координат вектора
$\\|\vec{a}|\\_1 = |a_1| + |a_2| + \dots + |a_n| = \sum_{i=1}^n |a_i|$ — $L_1$ норма;

In [ ]:
a = np.array([1, 3, 5])

# второй параметр - порядковый номер нормы
print(linalg.norm(a, 1))

9.0


Задача: в таблице собраны прайс-листы на некоторые материалы, которые компания закупает у двух поставщиков.

|  | 1 кг гвоздей | литр краски | молотки  |  паркет |
|-----------|-----|-------|-------|-------|
| магазин_1    | 150  | 2300    | 500  |  5000 |
| магазин_2    | 200  | 2500    | 600  |  4000 |

Необходимо рассчитать L1 норму для каждого магазина

In [57]:
shop_1 = np.array([100, 2300, 1000, 5000])
shop_2 = np.array([50, 2200, 600, 5700])

In [58]:
print(f'L1 for shop_1: {linalg.norm(shop_1, 1)}')
print(f'L1 for shop_2: {linalg.norm(shop_2, 1)}')

L1 for shop_1: 8400.0
L1 for shop_2: 8550.0


### L2 норма
корень из суммы квадратов всех координат
$\\|\vec{a}|\\_2 = \sqrt{a_1^2 + a_2^2 + \dots + a_n^2} = \sqrt{\sum_{i=1}^n a_i^2}$ — $L_2$ норма;

In [59]:
b = np.array([3, 4, 10])

# второй параметр - порядковый номер нормы
print(linalg.norm(b, 2))

11.180339887498949


In [66]:
b = np.array([3, 4, 10])

# по умолчанию считается L2 норма
print(linalg.norm(b))

11.180339887498949


In [60]:
# вычислим L2 норму для поставщиков
print(f'L2 for shop_1: {linalg.norm(shop_1, 2)}')
print(f'L2 for shop_2: {linalg.norm(shop_2, 2)}')

L2 for shop_1: 5594.640292279746
L2 for shop_2: 6139.421796879573


### Норма Чебышёва
максимум по модулю всех координат
$\\|\vec{a}|\\_\infty = \max_{i=1,\dots,n} |a_i|$ — $L_\infty$ норма;

In [64]:
c = np.array([3, 4, -20])

# второй параметр - порядковый номер нормы
print(linalg.norm(c, np.inf))

20.0


In [63]:
c

array([309,   6,  14,   7])

In [65]:
# вычислим L_inf норму для поставщиков
print(f'L_inf for shop_1: {linalg.norm(shop_1, np.inf)}')
print(f'Linf for shop_2: {linalg.norm(shop_2, np.inf)}')

L_inf for shop_1: 5000.0
Linf for shop_2: 5700.0


# Нахождение угла межд векторами
$$\cos(\vec{a}, \vec{b}) = \frac{\vec{a} \cdot \vec{b}}{|\vec{a}| \cdot |\vec{b}|}.$$

In [74]:
a = np.array([4, 8, 18])
b = np.array([-2, 3, 7])

cos_ab = a @ b / linalg.norm(a) / linalg.norm(b) # безразмерная величина

cos_ab_rad = np.arccos(cos_ab) # считаем в радианах
cos_ab_deg = np.rad2deg(cos_ab_rad) # переводим в градусы

print(f'Значение косинуса угла: {cos_ab}', f'Значение в радианах: {cos_ab_rad}', f'Значение в градусах: {cos_ab_deg}', sep='\n')

Значение косинуса угла: 0.8972259316387274
Значение в радианах: 0.45734972989860173
Значение в градусах: 26.20420928463804


In [75]:
k = np.array([12, 8, 3, 1])
i = np.array([0.7, 22, 5, 9])

i_k = i @ k

k_2 = linalg.norm(k)
i_2 = linalg.norm(i)

cos_ik = i_k / k_2 / i_2

cos_rad = np.arccos(cos_ik)
cos_deg = np.rad2deg(cos_rad)

print(cos_ik, cos_rad, cos_deg, sep='\n')

0.5808489307495451
0.9510251257999077
54.48972591923289


В пространстве расположен треугольник ABC. Координаты его вершин: A(7, 2, 11), B(5, 3, −4), C(−6, 8, 1).
Выведите на экран косинус ∠C 

In [ ]:
# задаем вектора от точки O=(0, 0, 0), которые идут до вершин треугольника
OA = np.array([7, 2, 11])
OB = np.array([5, 3, -4])
OC = np.array([-6, 8, 1])

# ищем координаты векторов, т.е. ребер треугольника: конец - начало
AC = OC - OA
BC = OC - OB

# ищем скалярное произведение AC и BC
a_c_sc = AC @ BC

# ищем L2 нормы
ac_2 = linalg.norm(AC)
bc_2 = linalg.norm(BC)

cos_angle_c = a_c_sc / (ac_2 * bc_2)
angle_rad = np.arccos(cos_angle_c)
angle_deg = np.rad2deg(angle_rad)

print(cos_angle_c, angle_rad, angle_deg, sep='\n')

0.5385885750266771
1.0020352608842744
57.41239137195931


# Расстояние между векторами
## через норму
- Расстояние норма разности двух векторов
- Норма может быть любой
- Расстояние между векторами для оценки похожести двух векторов вычисляют 
- Обычно это L2 норма. 

In [78]:
# найдем 3 основных расстояния между векторами a и b
a = np.array([22, 4, -6, 3.9, 7])
b = np.array([12, -0.5, 6, 42, 1])

r_1 = linalg.norm(a-b, 1)
r_2 = linalg.norm(a-b, 2)
r_inf = linalg.norm(a-b, np.inf)

print(f'L1 норма: {r_1}\nL2 норма: {r_2}\nL_inf норма: {r_inf}')

L1 норма: 70.6
L2 норма: 41.85522667481327
L_inf норма: 38.1


In [79]:
# неважно, что из чего вычитать - расстояние не изменится
linalg.norm(a-b, 1) == linalg.norm(b-a, 1), linalg.norm(a-b, 2) == linalg.norm(b-a, 2)

(True, True)

## через косинусное расстояние
- Так же для схожести векторов оценивают угол между ними
- Чем меньше угол - тем больше косинус => векторы более похожи
- Диапазон от -1 до 1

пример: есть 3 отзыва и нужно понять, какие из них похожи

1) Эти огурцы горькие, не понравились. Вердикт - не брать.
2) Огурцы отстой, не вкусные.
3) Супер, хрустят, рекомендую!

Выделим таблицу со всеми словами и посмотрим частоту слов в каждом отзыве. Получится 12 мерный вектор, который описывает отзыв

| эти |огрурцы | горькие | отстой | супер | не | понравились| вкусные | хрустят | вердикт | брать | рекомендую


In [80]:
# посчитаем кол-во слов в трех отзывах и посмотрим, какие отзывы похожи
o_1 = np.array([1, 1, 1, 0, 0, 2, 1, 0, 0, 1, 1, 0])
o_2 = np.array([0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0])
o_3 = np.array([0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1])

r_1_2 = linalg.norm(o_1-o_2)
r_1_3 = linalg.norm(o_1-o_3)
r_2_3 = linalg.norm(o_3-o_2)

print("Отзывы 1 и 2:", r_1_2)
print("Отзывы 1 и 3:", r_1_3)
print("Отзывы 2 и 3:", r_2_3)


Отзывы 1 и 2: 2.8284271247461903
Отзывы 1 и 3: 3.605551275463989
Отзывы 2 и 3: 2.6457513110645907


наименьшее расстояние между отзывами 2 и 3, но по своему содержанию отзывы вообще не похожи. Это связано с тем, что первый отзыв заметно длиннее других => у него больше нулевых значений. L2 норма учитывает размер векторов, поэтому разница отразилась в результатах. Нужно рассчитать косинусное расстояние

In [81]:
cos_1_2 = o_1 @ o_2 / linalg.norm(o_1) / linalg.norm(o_2)
cos_1_3 = o_1 @ o_3 / linalg.norm(o_1) / linalg.norm(o_3)
cos_2_3 = o_2 @ o_3 / linalg.norm(o_2) / linalg.norm(o_3)
print("Отзывы 1 и 2:", cos_1_2)
print("Отзывы 1 и 3:", cos_1_3)
print("Отзывы 2 и 3:", cos_2_3)


Отзывы 1 и 2: 0.4743416490252569
Отзывы 1 и 3: 0.0
Отзывы 2 и 3: 0.0


Чем ближе косинус к 1, тем более сонаправлены и близки векторы. Косинусное расстояние не учитывает масштаб векторов (а соответственно, и длину отзыва), поэтому результаты получились адекватные: больше всего похожи друг на друга отзывы 1 и 2.

Итог: Разные метрики хороши для разных ситуаций. Евклидово расстояние учитывает размеры векторов, и его используют для анализа числовых характеристик.

Косинусное расстояние не зависит от масштаба векторов и не чувствительно к числовым характеристикам. Зато оно подходит для оценки сходства текстов.


---
Иван решил контролировать свой бюджет и сравнивает средние цены продуктовой корзины с ценами в трёх магазинах
|  | гречка | рис | хлеб  |  сахар | яйца | свинина | молоко | творог |
|-----------|-----|-------|-------|-------|-------|-------|-------|-------|
| магазин_1    | 114  | 78    | 52  |  80 | 80 | 389 | 66 | 214 |
| магазин_2    | 155  | 180   | 87  |  79 | 83 | 451 | 77 | 412 |
| магазин_1    | 122  | 94    | 34  |  77 | 80 | 320 | 70 | 222 |
| корзина      | 116  | 96    | 38  |  63 | 80 | 469 | 73 | 300 |

In [2]:
m1 = np.array([114, 78, 52, 80, 80, 389, 66, 214])
m2 = np.array([155, 180, 87, 79, 83, 451, 77, 412])
m3 = np.array([122, 94, 34, 77, 70, 320, 70, 222])
avg = np.array([116, 96, 38, 63, 80, 469, 73, 300])


In [3]:
r1 = np.linalg.norm(m1 - avg)
r2 = np.linalg.norm(m2 - avg)
r3 = np.linalg.norm(m3 - avg)

In [4]:
print(r1, r2, r3, sep='\n')

121.07022755409358
155.32868376446123
169.25129246183025


цена на свинину резко отличается от остальных цен и сильно влияет на евклидово расстояние. Без неё результат получился бы следующим:

In [5]:
m1_ = np.array([114, 78, 52, 80, 80, 66, 214])
m2_ = np.array([155, 180, 87, 79, 83, 77, 412])
m3_ = np.array([122, 94, 34, 77, 70, 70, 222])
avg_ = np.array([116, 96, 38, 63, 80, 73, 300])

In [6]:
r1_ = np.linalg.norm(m1_ - avg_)
r2_ = np.linalg.norm(m2_ - avg_)
r3_ = np.linalg.norm(m3_ - avg_)

print(r1_, r2_, r3_, sep='\n')

90.87353850269065
154.2822089548889
80.2807573457052


На практике часто встречается ситуация, когда значения одного из признаков существенно отличаются от значений остальных. Влияние этого признака становится большим, хотя в реальности признаки должны быть равнозначимы. 

Чтобы сделать признаки равнозначимыми, их значения нормируют — приводят к единой шкале, например, к отрезку [0, 1]. Один из популярных способов такой: 

1.	Взять значения одного признака. Найти среди них наименьшее и наибольшее: Xmin и Xmax.
2.	Для каждого элемента этого признака вычислить нормированное значение по формуле $\frac{X - X_{\min}}{X_{\max} - X_{\min}}$
3.	Повторить шаги для остальных признаков.


In [16]:
np.stack([m1, m2, m3, avg])

array([[114,  78,  52,  80,  80, 389,  66, 214],
       [155, 180,  87,  79,  83, 451,  77, 412],
       [122,  94,  34,  77,  70, 320,  70, 222],
       [116,  96,  38,  63,  80, 469,  73, 300]])

In [ ]:
# axis=0 - работа по столбцам
np.stack([m1, m2, m3, avg]).max(axis=0)

array([155, 180,  87,  80,  83, 469,  77, 412])

In [ ]:
# axis=1 - работа по строкам - из каждого вектора берем максимум
np.stack([m1, m2, m3, avg]).max(axis=1)

array([389, 451, 320, 469])

In [18]:
np.stack([m1, m2, m3, avg]).min(axis=0)

array([114,  78,  34,  63,  70, 320,  66, 214])

In [32]:
matrix = np.stack([m1, m2, m3, avg])
matrix

array([[114,  78,  52,  80,  80, 389,  66, 214],
       [155, 180,  87,  79,  83, 451,  77, 412],
       [122,  94,  34,  77,  70, 320,  70, 222],
       [116,  96,  38,  63,  80, 469,  73, 300]])

In [33]:
# из первого столба вычитается 1, из второго 2
data = np.arange(1, 9)
matrix - data

array([[113,  76,  49,  76,  75, 383,  59, 206],
       [154, 178,  84,  75,  78, 445,  70, 404],
       [121,  92,  31,  73,  65, 314,  63, 214],
       [115,  94,  35,  59,  75, 463,  66, 292]])

In [34]:
def get_norm_matrix_min_max(matrix: np.ndarray) -> np.ndarray:
    min_values = matrix.min(axis=0)
    max_values = matrix.max(axis=0)

    return (matrix - min_values) / (max_values - min_values)

In [38]:
new_matrix = get_norm_matrix_min_max(np.stack([m1, m2, m3, avg]))

In [39]:
m1_norm = new_matrix[0]
m2_norm = new_matrix[1]
m3_norm = new_matrix[2]
avg_norm = new_matrix[3]

In [40]:
r1_norm = np.linalg.norm(m1_norm - avg_norm)
r2_norm = np.linalg.norm(m2_norm - avg_norm)
r3_norm = np.linalg.norm(m3_norm - avg_norm)

print(r1_norm, r2_norm, r3_norm, sep='\n')

1.408966048191791
1.960518327511826
1.5896481838452179
